name: Try to Create OCI VM

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-oci-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install and Run OCI Task
        env:
          OCI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_REGION: ${{ secrets.OCI_CLI_REGION }}
          OCI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_KEY: ${{ secrets.OCI_CLI_KEY_CONTENT }}
          AD_NAME: ${{ secrets.AD_NAME }}
          COMPARTMENT_ID: ${{ secrets.OCI_COMPARTMENT_ID }}
          IMAGE_ID: ${{ secrets.IMAGE_ID }}
          SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          SSH_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          # 1. 安装 OCI CLI
          bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oracle-cli/master/scripts/install/install.sh)" -- --accept-all-defaults || bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)" -- --accept-all-defaults
          export PATH=$PATH:/home/runner/bin
          
          # 2. 写入认证配置
          mkdir -p ~/.oci
          echo "$OCI_KEY" > ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/oci_api_key.pem
          
          CLEAN_USER=$(echo -n "$OCI_USER" | tr -d '[:space:]=')
          CLEAN_FINGERPRINT=$(echo -n "$OCI_FINGERPRINT" | tr -d '[:space:]=')
          CLEAN_TENANCY=$(echo -n "$OCI_TENANCY" | tr -d '[:space:]=')
